# Introduccion a Python

## Librerías

Python es un lenguaje de alto nivel cuya filosofía hace hincapié en una sintaxis muy limpia y que favorezca un código legible. Una de las grandes ventajas de Python es que la gran mayoría de código es abierto. El *Ecosistema de Python* está habitado por muchas bibliotecas o librerías que proporcionan herramientas útiles, como las operaciones matriciales (*arrays*), representaciones gráficas, etc. Podemos importar librerías de funciones para expandir las capacidades de Python en nuestros programas.

In [1]:
# Los comentarios en python se establecen con almohadillas

import numpy as np
# numpy es una librería que se esta importando y permite realizar operaciones matriciales estilo MATLAB.
# Para acceder a sus funciones se hará uso de una abreviatura mediante la siguiente nomenclatura "np.NombreDeLaFuncion".

import matplotlib.pyplot as plt 
# matplotlib es una librería para dibujar gráficas en 2D y 3D que se usará para representar los resultados.
# Accedemos al módulo pyplot dentro de la biblioteca matplotlib. 
# pyplot es un módulo que ofrece una interfaz de gráficos similar a la de MATLAB.
# En este caso se accedera a las funciones como "plt.NombreDeLaFuncion".

En resumen, mediante los comandos`import X as x`, se está importando la librería llamada `numpy` y una sub-librería o módulo de un paquete llamado `matplotlib`. Debido a que las funciones que queremos usar pertenecen a estas librerías, se debe indicar a Python de donde pertenecen cuando se llamen. Con las dos líneas superiores se han creado accesos directos a dichas librerías como `np` y `plt`, respectivamente.  Por tanto, si se requiere el uso de la función `linspace` contenida dentro de la biblioteca `numpy`, por ejemplo, se puede llamar de la siguiente forma:

In [3]:
myarray = np.linspace(0,50,10)
myarray

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

Si no se indica previamente a la función `linspace` con `np`, Python dará un error:

In [4]:
myarray = linspace(0,5,10)

NameError: name 'linspace' is not defined

En ocasiones, se puede observar código que importa la librería directamente sin usar una abreviatura para ello (como `np` para `numpy`). Aunque el acceso a las funciones será directo y ahorraría tiempo a la hora de escribir código, no es recomendable ya que lleva a errores posteriores. ¡Mejor adquirir buenas costumbres de programación desde un principio!

Para aprender las funciones que NumPy proporciona, podemos visitar la siguiente página [NumPy Reference](http://docs.scipy.org/doc/numpy/reference/). Si ya sabe programar en `MATLAB`, hay una página que le será de ayuda: [NumPy for Matlab Users](https://numpy.org/doc/stable/user/numpy-for-matlab-users.html).

Por último, se puede aprender a usar el módulo `pyplot` de la librería `matplotlib` a partir del [cuaderno sobre graficos](./B_09_Matplotlib_tutorial.ipynb).

## Variables

Python no requiere declarar explicitamente las variables tal y como ocurre en C y otros lenguajes de programación.  

In [5]:
a = 5      # a es el número entero (integer) 5
b = 'five' # b es una cadena de caracteres (string) con la palabra 'five'
c = 5.0    # c es el número de coma flotante (floating point) 5  

In [6]:
type(a)

int

In [7]:
type(b)

str

In [8]:
type(c)

float

## Espacios en Python

Python usa tabulaciones (*indents*) y espacios (*whitespaces*) para agrupar el contenido de una estructura de control (`for`, `while`, `if`). En realidad, el tabulado se compone por cuatro espacios en blanco y obliga a escribir código de forma ordenada. Un programa sin tabular correctamente nos devolverá un `IndentationError`. Este hecho permite además cerrar sentencias sin el uso de `end` lo que ayuda a la claridad del código de forma nativa. Por ejemplo, para escribir un bucle (*loop*) en `C`, se usaría:  

    for (i = 0, i < 5, i++){
       printf("Hola \n");
    }

Python, no usa llaves `{}` como `C` en el ejemplo anterior, por lo que el mismo programa escrito en Python quedaría como:

In [9]:
for i in range(5):
    print('Hola')

Hola
Hola
Hola
Hola
Hola


Si se tienen bucles anidados (*nested for-loops*) o unas estructuras de control dentro de otras, se debe añadir un tabulado en el interior. Por ejemplo para dos bucles for:

In [11]:
for i in range(8):
    for j in range(3):
        print(i,j)

0 0
0 1
0 2
1 0
1 1
1 2
2 0
2 1
2 2
3 0
3 1
3 2
4 0
4 1
4 2
5 0
5 1
5 2
6 0
6 1
6 2
7 0
7 1
7 2


## Trabajando con arrays

Un array es un conjunto de valores con el mismo tipo; esto es, todos sus elementos son enteros, reales en doble precisión, complejos en simple precisión, etc.

La clase array es más parecida a los arrays que se encuentran en `C` o en `Fortran` que a las matrices de `MATLAB`. Es importante destacar que <b>todas las operaciones aritméticas entre arrays se ejecutan elemento a elemento</b> y no como multiplicaciones matriciales tal y como ocurre en `MATLAB`.

En NumPy, se pueden seleccionar valores de arrays de forma similar que en `MATLAB`. Creamos un array con valores de 1 a 5:

In [12]:
myvals = np.array([1, 2, 3, 4, 5])
myvals

array([1, 2, 3, 4, 5])

Python indexa con la numeración a partir de cero (**zero-based index**), asi que vamos a ver el primer y último elemento en el array `myvals`:

In [13]:
myvals[0], myvals[4]

(1, 5)

Los arrays tambien pueden ser divididos o cortados (*sliced*) seleccionando un rango de valores. Veamos cómo seleccionar los tres primeros elementos:

In [14]:
myvals[0:3]

array([1, 2, 3])

Observamos que **la selección de elementos incluye el valor inicial y excluye el final**. El comando anterior devuelve los valores de `myvals[0]`, `myvals[1]` y `myvals[2]`, pero no de `myvals[3]`.

Python posibilita la utilización de índices negativos para numerar una secuencia desde el final. De esta forma, el elemento correspondiente al índice -1 será el último elemento de la secuencia:

In [15]:
myvals[-1]

5

## Asignando variables con array

Una de las funcionalidades en Python que suele confundir al usuario es la asignación y comparación de arrays de valores. Por ejemplo, definamos un array de una dimensión (1D) llamado $a$:

In [16]:
a = np.linspace(1,5,5)

In [17]:
a

array([1., 2., 3., 4., 5.])

Bien. Entonces tenemos un array $a$, con los valores del 1 al 5. Si quiero hacer una copia de este array, llamado $b$, haré lo siguiente: 

In [18]:
b = a

In [19]:
b

array([1., 2., 3., 4., 5.])

Genial. Entonces $b$ tiene ahora los valores del 1 a 5 tal y como tengo para $a$. Ya que tengo una copia de $a$, puedo cambiar sus valores sin preocuparme de perder datos (¡o eso puedo pensar!)

In [20]:
a[2] = 17

In [21]:
a

array([ 1.,  2., 17.,  4.,  5.])

Aquí el 3° elemento de $a$ se ha cambiado a 17.  Vamos ahora a comprobar que ha pasado con $b$.

In [22]:
b

array([ 1.,  2., 17.,  4.,  5.])

¡Y es aquí donde las cosas fallan! Cuando se usa una declaración del tipo $b = a$, más que copiar todos los valores de $a$ hacia un nuevo array llamado $b$, Python simplemente crea un alias (o puntero) llamado $b$ y lo referencia con $a$. Por lo que si cambiamos un valor en $a$ entonces $b$ reflejará ese cambio (técnicamente, esto se llama *assignment by reference*). 

Si se quiere realizar una **copia real** de un array, se tiene que decir a Python que copie todos los elementos de $a$ en un nuevo array $c$ el cual debe ser definido en primer lugar. Se trata entonces de un proceso en 2 etapas. Se puede definir un array "vacío" que sea de las mismas dimensiones que $a$ usando la funcion de numpy `empty_like`:

In [23]:
c = np.empty_like(a)

In [24]:
len(c) # muestra la longitud de c

5

In [25]:
c[:]=a[:] # copia los elementos de a en c

In [26]:
c

array([ 1.,  2., 17.,  4.,  5.])

Ahora, podemos probar de nuevo cambiar un valor de $a$ y ver si el cambio se refleja en $c$.  

In [27]:
a[2] = 3

In [28]:
a

array([1., 2., 3., 4., 5.])

In [57]:
c

array([ 1.,  2., 17.,  4.,  5.])

¡Funcionó! Puesto que el cambio **NO** se ve reflejado en `c`.

**NOTA**: Existe una forma más sencilla de copiar arrays en NumPy y es mediante la función `copy()`:

In [29]:
a = np.linspace(1,5,5)
d = np.copy(a)

In [59]:
d

array([1., 2., 3., 4., 5.])

In [60]:
a[2] = 17

In [61]:
a

array([ 1.,  2., 17.,  4.,  5.])

In [62]:
d

array([1., 2., 3., 4., 5.])

In [64]:
from IPython.core.display import HTML
css_file = '.././styles/numericalmoocstyle.css'
HTML(open(css_file, 'r').read())